name: Test Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (will not actually publish)'
        required: false
        default: 'true'
        type: boolean

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.15.0
          registry-url: "https://registry.npmjs.org"

      - name: Build package
        run: |
          # Simulate the build process
          echo "Simulating build..."
          mkdir -p dist
          echo "export default {}" > dist/index.mjs

      - name: Test npm publish
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "Running npm publish --dry-run"
            npm publish --dry-run
          else
            echo "Would run: npm publish --provenance --access public"
          fi

      - name: Check OIDC token
        run: |
          echo "Checking if OIDC token would be available..."
          # This will show if the OIDC token is properly configured
          if [[ -n "$NODE_AUTH_TOKEN" ]]; then
            echo "NODE_AUTH_TOKEN is set (length: ${#NODE_AUTH_TOKEN})"
          else
            echo "NODE_AUTH_TOKEN is not set"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}